### PR TITLE
feat(APIApplicationCommandIntegerOption): add `min_length` and `max_length`

### PR DESCRIPTION
**Pull request by dager-mohamed**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

### CODE REVIEW

**Comment by vladfrangu** [comment]
W-what?

**Comment by dager-mohamed** [comment]
> W-what?

if you see in https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure you will see `min-length` and `max-length` for command options

**Comment by vladfrangu** [comment]
Yes...only for string options, which is not where you added it...

**Comment by dager-mohamed** [comment]
> Yes...only for string options, which is not where you added it...

bro it is integer!

**Comment by dager-mohamed** [comment]
> Yes...only for string options, which is not where you added it...

image

**Comment by dager-mohamed** [comment]
> Yes...only for string options, which is not where you added it...

lol I added as a boolean in PR not an integer lol

**Comment by vladfrangu** [comment]
In fact, for integer/number options you use min/max_value (which are already present). min/max_length is only for string options (where it makes sense) 🙂 

The screenshot you sent refers to the data type you send to discord when specifying the option, *not* the option type! In this case, Discord is telling you that if you're specifying min/max_length the value needs to be an integer

**Comment by dager-mohamed** [comment]
> Yes...only for string options, which is not where you added it...

anyway I have been edited the pull request

**Comment by dager-mohamed** [comment]
> In fact, for integer/number options you use min/max_value (which are already present). min/max_length is only for string options (where it makes sense) slightly_smiling_face
> 
> The screenshot you sent refers to the data type you send to discord when specifying the option, _not_ the option type! In this case, Discord is telling you that if you're specifying min/max_length the value needs to be an integer

lol ok thx bro

**Pull request closed without merging**
