### PR TITLE
docs(UserFlags): update misleading `Hypesquad` description

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/4685

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Comment by ImRodry** [comment]
Why not Hypesquad Events Member? Looks kinda empty like this

**Comment by vladfrangu** [comment]
See the linked PR.

**Comment by ImRodry** [comment]
I did and that’s exactly why I suggested that

**Comment by vladfrangu** [comment]
Well suggest it there then, not here, we just match descriptions to discord's 🙂

**Comment by ImRodry** [comment]
they approved it

**Review by kyranet — APPROVED** [review]

**Review by vitorlops — COMMENTED** [review]
Think it's missing here
https://github.com/discordjs/discord-api-types/blob/e822e45b3b6e07eb85a45039975cb33636765f5e/deno/payloads/v8/user.ts#L99
and here
https://github.com/discordjs/discord-api-types/blob/8e87b3e1ce35201503623839602c44fe2a52a27b/payloads/v8/user.ts#L99

**Pull request merged**
