### PR TITLE
feat(APIGuildMember): add guild timeouts

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

**Reference Discord API Docs PRs or commits:**
- https://github.com/discord/discord-api-docs/pull/4075

### CODE REVIEW

**Review by ImRodry — CHANGES_REQUESTED** [review]
Shouldn't these be `string | null` and not optional?

**Comment by suneettipirneni** [comment]
> Shouldn't these be `string | null` and not optional?

yeah

**Comment by ImRodry** [comment]
I believe the property is still not optional though, seems to be present on every member fetch

**Comment by suneettipirneni** [comment]
> I believe the property is still not optional though, seems to be present on every member fetch

gonna wait until the docs PR get's settled and I'll update the prop.

**Comment by suneettipirneni** [comment]
Upstream PR merged

**Review by SpaceEEC — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
