### PR TITLE
feat(APIGuildMember): add `permissions`

### PR DESCRIPTION
**Pull request by dager-mohamed**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

### CODE REVIEW

**Comment by Mateo-tem** [comment]
Hmmm, but for that, doesn't exist `APIInteractionGuildMember`? Which contains the `permissions` property because is sent in an interaction 🤔

**Comment by dager-mohamed** [comment]
> Hmmm, but for that, doesn't exist `APIInteractionGuildMember`? Which contains the `permissions` property because is sent in an interaction thinking

I forgot to put it, wo I will make a commit now

**Comment by dager-mohamed** [comment]
> Hmmm, but for that, doesn't exist `APIInteractionGuildMember`? Which contains the `permissions` property because is sent in an interaction thinking

ok but  in `APIGuildMember` permissions doesn't exist

**Comment by Mateo-tem** [comment]
> ok but in `APIGuildMember` permissions doesn't exist, And `APIGuildMember`, `APIInteractionGuildMember` it is same

I mean, `APIInteractionGuildMember` has the `permissions` property
https://github.com/discordjs/discord-api-types/blob/main/payloads/v10/_interactions/base.ts#L51

`APIInteractionGuildMember` is only specified for interactions, where the `permissions` property is present

**Comment by dager-mohamed** [comment]
> > ok but in `APIGuildMember` permissions doesn't exist, And `APIGuildMember`, `APIInteractionGuildMember` it is same
> 
> ~I mean, `APIInteractionGuildMember` has the `permissions` property~ ~https://github.com/discordjs/discord-api-types/blob/main/payloads/v10/_interactions/base.ts#L51~
> 
> ~`APIInteractionGuildMember` is only specified for interactions, where the `permissions` property is present~
> 
> Sorry, ignore all of that, I misread the comment on the `permissions` property zany_face

no worries bro

**Comment by vladfrangu** [comment]
I stand by their question, why is this being added to the main guild member object? We have a type specifically for interaction members that is automatically used too 👀

**Comment by dager-mohamed** [comment]
> I stand by their question, why is this being added to the main guild member object? We have a type specifically for interaction members that is automatically used too eyes

ok but this will be available for interactions only !

**Comment by vladfrangu** [comment]
> > I stand by their question, why is this being added to the main guild member object? We have a type specifically for interaction members that is automatically used too eyes
> 
> ok but this will be available for interactions only !

Exactly! Since its only received for interactions it's defined there, and not on the main member object

**Comment by dager-mohamed** [comment]
> > > I stand by their question, why is this being added to the main guild member object? We have a type specifically for interaction members that is automatically used too eyes
> > 
> > 
> > ok but this will be available for interactions only !
> 
> Exactly! Since its only received for interactions it's defined there, and not on the main member object

mhmm, ok so I will close the pr you are right

**Pull request closed without merging**
