### PR TITLE
feat(Message): reply updates

### PR DESCRIPTION
**Pull request by advaith1**
whether a reply should ping the author of the original message

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]
Waiting on Discord to either get a PR or mention this somewhere, otherwise LGTM

**Comment by advaith1** [comment]
it's in the replies pr now

but now channel_id in allowed 
_mentions is optional so I can add that to this pr

**Review by vladfrangu — CHANGES_REQUESTED** [review]
Before we can merge this, https://github.com/discordjs/discord-api-types/pull/34/files#diff-df009aedf43eb83e065b2a738b64184c0e6d5fd592a9d9216be0354c761d0a2fR79 needs an update because the messageID would be required if you are sending a message_reference

**Comment by advaith1** [comment]
so should we make a different interface for sending? in docs it's the same object

**Comment by vladfrangu** [comment]
No.. `Required<APIMessageReference> & Omit<APIMessageReference, 'message_id'> ` or similar

**Review by vladfrangu — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
