### PR TITLE
fix: add missing gateway dispatch payloads to gateway event union

### PR DESCRIPTION
**Pull request by john-batch**
GatewayDispatchEvents.ApplicationCommandPermissionsUpdate currently lacks an associated DataPayload. This pull request fixes that.

Related links :
https://discord.com/developers/docs/topics/gateway-events#application-command-permissions-update
https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-guild-application-command-permissions-structure

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Comment by vladfrangu** [comment]
If this PR closes #617 then please mark it as such! 🙏

**Comment by john-batch** [comment]
I will, but I noticed that `GatewayDispatchPayload` doesn't include all dispatch payloads in the union, namely :
```
GatewayAutoModerationRuleModifyDispatch
GatewayAutoModerationRuleCreateDispatch
GatewayAutoModerationRuleDeleteDispatch
GatewayAutoModerationActionExecutionDispatch
```
They're already declared in gateway/v10, so do you want me to add them to the union as part of this PR or to create a new one ?

**Comment by vladfrangu** [comment]
Do it in this PR if you can! 🙏

**Review by kyranet — APPROVED** [review]

**Comment by vladfrangu** [comment]
Can you do this for v9 too or is it not needed there?

**Comment by john-batch** [comment]
Should I add `GatewayApplicationCommandPermissionsUpdateDispatch` to the v9 declaration as well ? I'm not too familiar with how application commands works in v9.

**Comment by vladfrangu** [comment]
The only differences between API v9 and v10 is threads! So, yes please!

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
