### PR TITLE
feat: api v10

### LINKED ISSUE #330: Add support for Discord API v10
**Is your feature request related to a problem? Please describe.**
It is the new stable API version from discord. New features will only be released at v10+

**Describe the ideal solution**
Switch from API v9 to  API v10

**Additional context**
API Release:  https://github.com/discord/discord-api-docs/discussions/4510

### PR DESCRIPTION
**Pull request by vladfrangu**
**Please describe the changes this PR makes and why it should be merged:**

Closes #330 (too fast 😔)

If you want to help out with the changes in v10 (read https://github.com/discord/discord-api-docs/discussions/4510), feel free to PR to the branch on my fork.

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/discussions/4510

### CODE REVIEW

**Comment by almeidx** [comment]
😁
- https://github.com/vladfrangu/discord-api-types/pull/4

**Comment by SuperchupuDev** [comment]
- https://github.com/vladfrangu/discord-api-types/pull/3

**Comment by vladfrangu** [comment]
Awaiting replies on

- https://github.com/discord/discord-api-docs/discussions/4510#discussioncomment-2176935
- [ALL VERSIONS] application.summary now returns an empty string. This field will be removed in v11

**Comment by vladfrangu** [comment]
I think we're ready for v10 types 🎉

**Review by kyranet — APPROVED** [review]

**Pull request merged**
