### PR TITLE
feat(UserPremiumType): add `NitroBasic`

### PR DESCRIPTION
**Pull request by Mateo-tem**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/5568

### CODE REVIEW

**Comment by Jiralite** [comment]
Is this actually right? Isn't this completely breaking?

**Comment by Mateo-tem** [comment]
> Is this actually right? Isn't this completely breaking?

This is supposed to be right, Nitro Basic was officially announced and is being rolled out since today. Discord is using `PREMIUM_TIER_0` for Nitro Basic.

**Comment by Jiralite** [comment]
I think I interpreted 0 as no Nitro rather than unused, I guess...

**Comment by Mateo-tem** [comment]
Now, if you don't have nitro, the user object will return the `premium_type` property as `null`.

**Comment by vvito7** [comment]
It wouldn't really make sense, https://github.com/discord/discord-api-docs/pull/5568 is probably the way it is being done

**Comment by panley01** [comment]
I bought the new nitro to check and, yep, comes in as 3

afaik it *was* 0 with no nitro being set to -1 or the field being made nullable but that caused too many issues because it was (obviously) a breaking change. As of the rollout this week, it's 3.

**Comment by Mateo-tem** [comment]
Oh well, it seems to be a last-minute change, I found this, it should be the cause of the change?
discord com_channels_613425648685547541_697216494760886393

**Comment by Mateo-tem** [comment]
I bought Nitro Basic and now I can confirm that it is 3. I will change it and sorry for the confusion.

**Review by kyranet — APPROVED** [review]

**Pull request merged**
