### PR TITLE
feat: role subscriptions

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- discord/discord-api-docs#5724

### CODE REVIEW

**Comment by almeidx** [comment]
Upstream PR merged

**Review by kyranet — APPROVED** [review]

**Comment by vladfrangu** [comment]
This needs a rebase

**Comment by vladfrangu** [comment]
this needs a rebase

**Comment by almeidx** [comment]
Rebased

**Pull request merged**
