### PR TITLE
feat(Routes): Add `guildBulkBan()` route

### PR DESCRIPTION
**Pull request by codershiba**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/6720

### CODE REVIEW

**Comment by vladfrangu** [comment]
Please clone the repo locally and lint your changes! See the https://discord-api-types.dev/docs/contributing_to_discord-api-types guide

**Comment by codershiba** [comment]
> Please clone the repo locally and lint your changes! See the https://discord-api-types.dev/docs/contributing_to_discord-api-types guide

Done

**Comment by sdanialraza** [comment]
Those are in separate PRs I believe: #908 #910

**Comment by codershiba** [comment]
> ~Still not linted Also you should add interfaces for params / result from the endpoint and the error code~

I don't see any issues being reported when I run `npm run lint`

**Review by almeidx — APPROVED** [review]

**Pull request merged**
