### PR TITLE
fix(APIApplicationCommand): default_permission

### PR DESCRIPTION
**Pull request by vaporox**
**Reference Discord API Docs PRs or commits:**

discord/discord-api-docs#2737

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]
Lord spare me

**Comment by advaith1** [comment]
this was actually a mistake in the docs pr iirc

**Comment by vladfrangu** [comment]
It wasn't

**Comment by advaith1** [comment]
https://github.com/discord/discord-api-docs/pull/2737#discussion_r601797055

**Comment by vladfrangu** [comment]
Right, the documentation is wrong right now (not a first timer for the docs 😬)... submit a PR to fix it :D

**Pull request merged**
