### PR TITLE
feat(ApplicationFlags): add new flags

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**

**Reference Discord API Docs PRs or commits:**
- https://github.com/discord/discord-api-docs/pull/4248

### CODE REVIEW

**Comment by almeidx** [comment]
I noticed there were a few flags in the enums that are not documented on Discord's side, but I chose to not remove them as to not make this a breaking pull request

Should those be removed (perhaps in a separate pull request)?

**Comment by kyranet** [comment]
I personally would either remove or deprecate them (as undocumented). cc @vladfrangu

**Comment by vladfrangu** [comment]
They're staying, as they're present in the dev portal's source (and are one of those "well maybe you need them but they're not considered important to bots for Discord")

**Review by vladfrangu — APPROVED** [review]

**Comment by kyranet** [comment]
Thank you for your contribution, however, the upstream PR has been closed as Discord does not want to document those flags.

**Comment by vladfrangu** [comment]
Could you restore the branch when you have time? I want this merged since there's direct relations to one of these flags in a separate interface (specifically APIInvite)

**Comment by almeidx** [comment]
It doesn't let me open the pull request again

Here's a new one:
- https://github.com/discordjs/discord-api-types/pull/277

**Pull request closed without merging**
