### PR TITLE
 chore(APIGuildMember): mark `joined_at` as nullable

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

- https://github.com/discord/discord-api-docs/pull/4824

### CODE REVIEW

**Comment by vladfrangu** [comment]
_Semver majors yay_

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by almeidx** [comment]
The comment should be updated too

**Comment by yonilerner** [comment]
Warning: https://github.com/discord/discord-api-docs/pull/4824#issuecomment-1108813426

**Review by kyranet — APPROVED** [review]

**Comment by yonilerner** [comment]
shut it down :(

**Pull request closed without merging**
