### PR TITLE
feat(routes): add guild member banner route

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

- https://github.com/discord/discord-api-docs/pull/4955

### CODE REVIEW

**Comment by suneettipirneni** [comment]
CI failing for reasons outside of this PR

**Comment by vladfrangu** [comment]
Isn't this a CDN route which we currently don't have documented? 😅 

We should probably create an object with CDNRoutes instead (and the cdn is a constant)

**Comment by suneettipirneni** [comment]
Oh yeah, my bad 🤦

**Review by kyranet — APPROVED** [review]

**Comment by vladfrangu** [comment]
Closing this as it was added in #502 instead

**Pull request closed without merging**
