### PR TITLE
feat: default select menu values

### PR DESCRIPTION
**Pull request by jaw0r3k**
**Please describe the changes this PR makes and why it should be merged:**

copilot:summary

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/6442#issuecomment-1728519608

### CODE REVIEW

**Comment by vladfrangu** [comment]
Do we need to add https://github.com/discord/discord-api-docs/pull/6442/files#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95R302 too?

**Comment by Renegade334** [comment]
Testing confirms that calling the API with default select menu objects that are type-mismatched from the parent select menu component (_eg._ providing a select menu component with `type: ComponentType.UserSelect` but giving a default select menu object of `type: "channel"`) returns a `DiscordAPIError[50035]: Invalid Form Body`.

Accordingly, I think the default select menu value type needs to be templated such that `type` is constrained to match its parent select menu component.

**Comment by vladfrangu** [comment]
I was referring to the resolved values, but you can also strictly type the default values if you want!

**Comment by Renegade334** [comment]
@jaw0r3k: I've addressed the `APIMessage` change in Renegade334@58b65c8778321b690aba056bac2bb4338cf418f4 and the default value type narrowing in Renegade334@33cbceac2e12b88dfb0dddc8cfb1f12bb790a944 - pull/modify/steal at your leisure

**Review by vladfrangu — APPROVED** [review]

**Review by almeidx — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]

**Pull request merged**
