### PR TITLE
feat(PermissionFlagBits): update thread permissions

### PR DESCRIPTION
**Pull request by advaith1**
* https://github.com/discord/discord-api-docs/pull/3672

### CODE REVIEW

**Review by moritz-mn — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
We could make this sem minor by still providing the old names, with an `@deprecated` tag, so users in 13.2 or whatever version can use SendMessagesInThread... Nonetheless, LGTM

**Comment by vladfrangu** [comment]
Wait. This is -types

**Comment by vladfrangu** [comment]
This needs a rebase

**Comment by vladfrangu** [comment]
Should we include these in v8 too, even if it doesn't include threads? @advaith1 @discordjs/the-big-3

**Comment by ImRodry** [comment]
I mean the permission bits will still be there on v8 so why not

**Comment by advaith1** [comment]
well all the thread rest stuff and permissions are in API v8 too, but we don't include them so 🤷‍♂️

**Comment by vladfrangu** [comment]
Honestly I'm considering just.. moving permission bit fields to common.ts since they're the same across API versions

**Comment by advaiu-pro** [comment]
Narain Kumar Jagathesan, (510) 794-5608, 2880 Predio Ter, Fremont, CA

**Comment by advaiu-pro** [comment]
@advaith1 dad Narain Kumar Jagathesan, (510) 794-5608, 2880 Predio Ter, Fremont, CA

**Pull request merged**
