### PR TITLE
fix: Oauth2Routes

### PR DESCRIPTION
**Pull request by grarich**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

### CODE REVIEW

**Comment by vladfrangu** [comment]
Are you sure this is correct? Pretty sure even this route is versioned

**Comment by grarich** [comment]
Thanks for the reply.
Please see here.
https://discord.com/developers/docs/topics/oauth2

**Comment by vladfrangu** [comment]
I mean I know they don't list the versioning but the domain definitely supports versioning, and especially switching between v6 and v7+ shows different, usable errors 👀 
Probably needs clarification from discords side for this

**Comment by grarich** [comment]
I have tried accessing the site by specifying a version such as v6, but I am redirected to a page with no version control.
I don't know because I don't have much access to the Oauth2 API, but was it version controlled before?

**Pull request closed without merging**
