### PR TITLE
feat(RESTJSONErrorCodes): add error `100053`

### PR DESCRIPTION
**Pull request by Mateo-tem**
**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/5588

### CODE REVIEW

**Review by Jiralite — CHANGES_REQUESTED** [review]
You made a typo.

**Comment by Mateo-tem** [comment]
> You made a typo.

Sorry, that was in the upstream PR. 😅

**Comment by Lulalaby** [comment]
Sorry :D

**Comment by Mateo-tem** [comment]
> Sorry :D

No problem ;)

**Comment by kyranet** [comment]
The upstream PR closed.

**Comment by vladfrangu** [comment]
Closing as we only merge bot-related additions.

**Pull request closed without merging**
